apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: tax-calculator-run
spec:
  pipelineRef:
    name: tax-calculator-pipeline

  params:
    - name: repo-url
      value: https://github.com/TanuRana0207/zntwk-tax_calculator.git
    - name: repo-revision
      value: main
    - name: pathToDockerFile
      value: ./Dockerfile

  workspaces:
    - name: shared-workspace
      emptyDir: {}
